sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky
    username: root
    password: 123456
  alioss:
    endpoint:
    bucket-name:
    access-key-id:
    access-key-secret:
  redis:
    host: localhost
    port: 6379
    database: 0
  base-path: D:\WorkProject\sky-images\