sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky
    username: root
    password: 123456
  alioss:
    endpoint:
    bucket-name:
    access-key-id:
    access-key-secret:
  redis:
    host: localhost
    port: 6379
    database: 0
  base-path: D:\WorkProject\sky-images\
  wechat:
    appid: xxx
    secret: xxx
    mchid: xxx
    mch-serial-no: yyy
    private-key-file-path: xxx
    api-v3-key: yyy
    we-chat-pay-cert-file-path: xxx
    notify-url: yyy
    refund-notify-url: xxx